spring.application.name=gamebarsmemberclub

server.port=${PORT:8080}
server.servlet.session.tracking-modes=cookie

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath*:/mybatis/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.example.app.domain

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

app.member.common-password=1234
spring.messages.basename=messages,validation

logging.level.org.springframework.context.support=DEBUG
logging.level.org.springframework.security=DEBUG
spring.mvc.log-request-details=true
logging.level.org.springframework.web.servlet.handler=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG